AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serendipity
  
  Sample SAM Template for serendipity

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  serendipity:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: main/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            Path: /
            Method: POST
      Environment: 
        Variables:
          TG_TOKEN: VALUE

Outputs:
  APIEndpoint:
    Description: "API Gateway endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

